name: Python Code Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check Python syntax
        run: |
          python -m py_compile sensor_simulator/*.py || true
          python -m py_compile data_processing/lambda/*.py || true
          python -m py_compile dashboard_EC2/app/*.py || true
